### PR TITLE
fixed as_str error with rustc 1.4.0-nightly 

### PR DESCRIPTION
**Pull request by geraldstanje**

### CODE REVIEW

**Comment by geraldstanje** [comment]
fixed with pull request https://github.com/sivadeilra/racc/pull/8

**Comment by geraldstanje** [comment]
hi, can you merge this?

**Comment by geraldstanje** [comment]
whats are the next steps? do you plan to contribute again anytime soon?

**Comment by sivadeilra** [comment]
I basically stopped working on RACC when it became clear that the Rust AST
API was still changing a lot, and that the extension API for accessing it
in a compile-time extension was also going to change quite a lot.  When it
stabilizes, I might contribute more.

Are you doing something specific with RACC?  Feel free to use it or
contribute to it.  It's just a side project of mine.

**Pull request merged**
